### ISSUE TITLE
ragdoll universe script not working (the multi hack doesnt work.)

### ISSUE THREAD

**Issue by Muhammadquran** [AlexR32/Roblox#3]
The ragdoll universe script gui does not open, it does execute, as i see in the console. fix this? (EDITED PART) in fact,the multi loader doesnt even work!

**Comment by AlexR32** [comment]
check out parvus hub https://github.com/AlexR32/Parvus it has ragdoll universe and other games

**Comment by Muhammadquran** [comment]
got it, thank you
