### ISSUE TITLE
BRM5 | When will work

### ISSUE THREAD

**Issue by cristiandonaraDEV** [AlexR32/Roblox#5]
this will work again?

**Comment by cristiandonaraDEV** [comment]
The error inìs only in this code

```
local Network = {}
for Index, Table in pairs(getgc(true)) do
    if typeof(Table) == "table"
    and rawget(Table,"FireServer")
    and rawget(Table,"InvokeServer") then
        function Network:FireServer(...)
            Table:FireServer(...)
        end
        function Network:InvokeServer(...)
            Table:InvokeServer(...)
        end
        break
    end
end
```


Maybe it can be fixed, i never worked on roblox scripts  before, but i know u can do it

**Comment by AlexR32** [comment]
No i will not continue to support brm5 autofarm script.
Also this is not the error, this code is totally fine.

**Comment by TarikDaGamer** [comment]
> No i will not continue to support brm5 autofarm script. Also this is not the error, this code is totally fine.

Why?

**Comment by TarikDaGamer** [comment]
> No i will not continue to support brm5 autofarm script. Also this is not the error, this code is totally fine.

Also it is not.
The typeof function should be capitalized as typeof(). Here's the corrected code:

local Network = {}
for Index, Table in pairs(getgc(true)) do
    if typeof(Table) == "table"
    and rawget(Table,"FireServer")
    and rawget(Table,"InvokeServer") then
        function Network:FireServer(...)
            Table:FireServer(...)
        end
        function Network:InvokeServer(...)
            Table:InvokeServer(...)
        end
        break
    end
end
